### ISSUE TITLE
Conditional rendering based on roles/permissions

### ISSUE THREAD

**Issue by macfire** [tonyseek/flask-navigation#14]
@tonyseek can suggest a way to handle conditional render of nav items based on role/permissions? 
I have functioning `@roles_required('role-name')` on my routes. I would like to not render a link if the User does not have permission to that route.

Thanks.

**Comment by tonyseek** [comment]
I think it could be done in your template:

``` jinja
<ul>
    {% for item in nav.top if have_permission(current_user, item.ident.endpoint) %}
    <li class="{{ 'active' if item.is_active else '' }}">
        <a href="{{ item.url }}">{{ item.label }}</a>
    </li>
    {% endfor %}
</ul>
```
