### ISSUE TITLE
Render HTML like WTForm

### ISSUE THREAD

**Issue by shonenada** [tonyseek/flask-navigation#3]
Maybe we can improve inerfaces in rendering html like:

``` html+jinja
<ul>
    {% for item in nav.top %}
    <li class="{{ 'current' if item.is_active else '' }}">
        {{ item.a(class="some_style", id="some_id") }}
    </li>
    {% endfor %}
</ul>
```

**Comment by tonyseek** [comment]
It seems the feature could be done with the [MarkupSafe's protocol](https://pypi.python.org/pypi/MarkupSafe#html-representations).

@shonenada Could you implement it and send me a pull request?
